routes/web.php
<?php

use App\Battle;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    $battle = new Battle;
    $battle = $battle->orderByDesc('updated_at')->paginate(10);

    return view('home')
        ->with('battle', $battle);

})->name('homepage');


Route::get('/battle/vote', 'App\BattleController@vote');
Route::resource('battle', 'App\BattleController');


// Route::get('/battle/{id}', 'BattleController@show');

app/Battle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Battle extends Model
{
    protected $table = 'battle';
    protected $guarded = ['id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/helpers.php
<?php


function currentUrl() {
  $url  = @( $_SERVER["HTTPS"] != 'on' ) ? 'http://'.$_SERVER["SERVER_NAME"] :  'https://'.$_SERVER["SERVER_NAME"];
  $url .= ( $_SERVER["SERVER_PORT"] !== 80 ) ? ":".$_SERVER["SERVER_PORT"] : "";
  $url .= $_SERVER["REQUEST_URI"];
  return $url;
}

app/Http/Controllers/App/BattleController.php
<?php

namespace App\Http\Controllers\App;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Battle;

class BattleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $battle = new Battle;
        // $battle = $battle->all();
        //
        // return view('index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Battle $battle)
    {
        $validatedData = $request->validate([
            'team1' => 'required',
            'team2' => 'required',
            'first_team_img' => 'required|image|mimes:jpg,jpeg,png,gif',
            'second_team_img' => 'required|image|mimes:jpg,jpeg,png,gif',
        ]);

        $first_team = $request->team1;
        $second_team = $request->team2;

        $images = ['first_team_img', 'second_team_img'];




        foreach ($images as $file) {
            if ($request->hasFile($file)) {

                $image = $request->file($file);

                $image_id = md5($image->getClientOriginalName() . time()) . "." . $image->getClientOriginalExtension();
                $destinationPath = public_path('storage/images/');
                $image->move($destinationPath, $image_id);

                $battle->{$file} = $image_id;
            }
        }


        $battle->first_team = $first_team;
        $battle->second_team = $second_team;
        $battle->save();

        return redirect("/battle/$battle->id");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $battle = new Battle;
        $battle = $battle->find($id);

        return view('show')
            ->with('battle', $battle);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    public function vote(Request $request)
    {
        $validatedData = $request->validate([
            'id' => 'required',
            'team' => 'required',
        ]);

        $battle = new Battle;
        $id = $request->id;
        $teamvotes = $request->team;


        $battle = $battle->find($id);
        $battle->{$teamvotes}++;
        $battle->save();

        $result['status'] = 1;
        $result['msg'] = 'success';
        return $result;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/create.blade.php
@extends('index')

@section('pageTitle', 'Onversus Battle Create')
@section('facebook_meta')
<meta property="og:url"           content="{{ currentUrl() }}" />
<meta property="og:type"          content="website" />
<meta property="og:description"   content="Onversus Battle" />
<meta property="og:title"         content="Создай батл и выясни кто круче" />
<meta property="og:image"         content="<?php echo asset("images/opg_image.jpg")?>"/>
@endsection


@section('content')

<div class="row row-first">
    <div class="col-md-6 col-md-offset-3">


        <form method="post" class="form-horizontal" action="{{ route('battle.store') }}"
        enctype="multipart/form-data">
            {{ csrf_field() }}


            <div class="form-group">
                <div class="col-sm-10">

                    <h1 class="text-center"><span style="color:#2c6ccc">on</span>versus </h1>

                    <hr>

                    <input type="text" class="text-center form-control" id="team1" placeholder="Команда 1" name="team1">
                    <input type="file" name="first_team_img" id="first_team_img">
                    <input type="hidden" value="{{ csrf_token() }}" name="_token">
                </div>
            </div>




            <div class="form-group">
                <div class="col-sm-10">
                    <input type="text" class="text-center form-control" value="VS" disabled>
                </div>
            </div>


            <div class="form-group">
                <div class="col-sm-10">
                    <input type="text" class="text-center form-control" id="team2" placeholder="Команда 2" name="team2">
                    <input type="file" name="second_team_img" id="second_team_img">
                    <input type="hidden" value="{{ csrf_token() }}" name="_token">
                </div>
            </div>

            <hr>

            <div class="form-group">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary btn-create">Начать Батл !</button>
                </div>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('index')

@section('pageTitle', 'Onversus Battle Home')
@section('facebook_meta')
<meta property="og:url"           content="{{ currentUrl() }}" />
<meta property="og:type"          content="website" />
<meta property="og:title"         content="Onversus Battle Homepage" />
<meta property="og:description"   content="Создай батл и проверь кто круче" />
<meta property="og:image"         content="<?php echo asset("images/opg_image.jpg")?>"/>
@endsection

@section('content')
<div class="row row-first">
    <div class="battlemainparent">
        <app-name></app-name>
        <app-citate></app-citate>
        <div class="text-center">
            <a href="{{ route('battle.create') }}" class="btn btn-success btn-lg">Создать Новый Батл</a>
        </div>
        @foreach($battle as $item)
            <div class="col-md-4">
            <div class="versusparent" id="{{ $item->id }}">
                <div class="versusbody">
                    <div v-on:click="vote({{ $item->id }}, 'first_team_votes')" class="vsteam">
                        <img src="storage/images/{{ $item->first_team_img }}" class="vsteamimage">
                        <div class="team-name">{{ $item->first_team }}

                        <div class="team-votes" ref="first_team_votes_{{ $item->id }}">{{ $item->first_team_votes }}</div>

                        </div>

                    </div>
                    <div class="versus">
                        VS
                    </div>
                    <div v-on:click="vote({{ $item->id}}, 'second_team_votes')" class="vsteam">
                        <img src="storage/images/{{ $item->second_team_img }}" class="vsteamimage">
                        <div class="team-name">{{ $item->second_team }}

                            <div class="team-votes" ref="second_team_votes_{{ $item->id }}">{{ $item->second_team_votes }}</div>

                        </div>
                    </div>
                </div>
                <div class="versusmeta">
                    <a href="{{ route('battle.show', $item) }}">
                        <div class="commentsparent">
                        Комментировать
                    </div>
                    </a>
                </div>
            </div>
        </div>
        @endforeach

        {{ $battle->links() }}
    </div>
</div>


<!-- <app-start></app-start> -->
<!-- <p>@{{ title }}</p>
<p>@{{ inputtext }}</p>
<p v-bind:class="style">@{{ style }}</p> -->
<!-- <div>@{{ value }}</div>
<div>@{{ doublevalue }}</div>
<div>@{{ message | lowercase }}</div>
<input tyle="text" value="" v-on:input="increment ($event.target.value)" />
<li v-for="car in cars">Модель @{{ car.model }}, Скорость @{{ car.speed }}</li> -->

@endsection

resources/views/includes/header.blade.php
<head>
    <title>@yield('pageTitle')</title>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="author" content="Afgan Khalilov">

    @yield('facebook_meta')
    <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/images/favicon.ico" type="image/x-icon">


    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
    <link href="{{ asset('/css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

resources/views/includes/navbar.blade.php
<!-- <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">onversus</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="/">Все Батлы</a></li>
        <li><a href="{{ route('battle.create') }}">Создать Батл</a></li>
      </ul>
    </div>
  </div>
</nav> -->




{{-- Bootstrap 4 Navbar --}}
<!-- <nav class="navbar navbar-fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Onversus</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Battles</a>
      </li>
    </ul>
  </div>
</nav> -->

resources/views/index.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>


        @include('includes.header')

    </head>
    <body>
        <div id="app">
            <app-navbar></app-navbar>
            <div class="container">
                @yield('content')
            </div>
        </div>


        <script src="{{ asset('js/app.js') }}"></script>
    </body>
</html>

resources/views/show.blade.php
@extends('index')

@section('pageTitle', 'Onversus Battle Detail')
@section('facebook_meta')
<meta property="og:url"           content="{{ currentUrl() }}" />
<meta property="og:type"          content="website" />
<meta property="og:title"   content="{{ $battle->first_team }} vs {{ $battle->second_team }} - Кто Круче ?" />
<meta property="og:description"         content="Onversus Battle" />
<meta property="og:image"         content="<?php echo asset("images/opg_image.jpg")?>"/>
@endsection


@section('content')

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v2.12';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>


<div class="row row-first">
    <div class="battledetailparent">
        <div class="row">
            <div class="col-md-5">
                <div class="versusparent">
                    <div class="versusbody">
                        <div  v-on:click="vote({{ $battle->id }}, 'first_team_votes')" class="vsteam">
                            <img src="<?php echo asset("storage/images/$battle->first_team_img")?>" class="vsteamimage"></img>
                            <div class="team-name">{{ $battle->first_team }}

                                <div class="team-votes" ref="first_team_votes_{{ $battle->id }}">{{ $battle->first_team_votes }}</div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="versuscitate">
                    <span>VS</span>
                </div>
            </div>
            <div class="col-md-5">
                <div class="versusparent">
                    <div class="versusbody">
                        <div v-on:click="vote({{ $battle->id }}, 'second_team_votes')" class="vsteam">
                            <img src="<?php echo asset("storage/images/$battle->second_team_img")?>" class="vsteamimage"></img>
                            <div class="team-name">{{ $battle->second_team }}

                                <div class="team-votes" ref="second_team_votes_{{ $battle->id }}">{{ $battle->second_team_votes }}</div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">



            <div class="col-md-12 text-center">
                <!-- Your share button code -->
                <div class="fb-share-button"
                data-href="{{ currentUrl() }}"
                data-layout="button_count"
                data-size="large">
                </div>
            </div>

        <div class="fb-comments"  data-href="{{ currentUrl() }}" data-numposts="20" data-colorscheme="light" data-mobile="true" data-order-by="reverse_time"></div>

        </div>
    </div>
</div>


<!-- <div class="versus">
    VS
</div>
<div class="vsteam">
    <div>Mercedes</div>
    <div>1685</div>
</div> -->
@endsection